// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/forwarder/forwarder.proto

package forwarder

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ForwarderService_RegisterChannelSession_FullMethodName = "/forwarder.ForwarderService/RegisterChannelSession"
	ForwarderService_RemoveChannelSession_FullMethodName   = "/forwarder.ForwarderService/RemoveChannelSession"
)

// ForwarderServiceClient is the client API for ForwarderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ForwarderServiceClient interface {
	RegisterChannelSession(ctx context.Context, in *RegisterChannelSessionRequest, opts ...grpc.CallOption) (*RegisterChannelSessionResponse, error)
	RemoveChannelSession(ctx context.Context, in *RemoveChannelSessionRequest, opts ...grpc.CallOption) (*RemoveChannelSessionResponse, error)
}

type forwarderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewForwarderServiceClient(cc grpc.ClientConnInterface) ForwarderServiceClient {
	return &forwarderServiceClient{cc}
}

func (c *forwarderServiceClient) RegisterChannelSession(ctx context.Context, in *RegisterChannelSessionRequest, opts ...grpc.CallOption) (*RegisterChannelSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterChannelSessionResponse)
	err := c.cc.Invoke(ctx, ForwarderService_RegisterChannelSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forwarderServiceClient) RemoveChannelSession(ctx context.Context, in *RemoveChannelSessionRequest, opts ...grpc.CallOption) (*RemoveChannelSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveChannelSessionResponse)
	err := c.cc.Invoke(ctx, ForwarderService_RemoveChannelSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForwarderServiceServer is the server API for ForwarderService service.
// All implementations must embed UnimplementedForwarderServiceServer
// for forward compatibility.
type ForwarderServiceServer interface {
	RegisterChannelSession(context.Context, *RegisterChannelSessionRequest) (*RegisterChannelSessionResponse, error)
	RemoveChannelSession(context.Context, *RemoveChannelSessionRequest) (*RemoveChannelSessionResponse, error)
	mustEmbedUnimplementedForwarderServiceServer()
}

// UnimplementedForwarderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForwarderServiceServer struct{}

func (UnimplementedForwarderServiceServer) RegisterChannelSession(context.Context, *RegisterChannelSessionRequest) (*RegisterChannelSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterChannelSession not implemented")
}
func (UnimplementedForwarderServiceServer) RemoveChannelSession(context.Context, *RemoveChannelSessionRequest) (*RemoveChannelSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveChannelSession not implemented")
}
func (UnimplementedForwarderServiceServer) mustEmbedUnimplementedForwarderServiceServer() {}
func (UnimplementedForwarderServiceServer) testEmbeddedByValue()                          {}

// UnsafeForwarderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForwarderServiceServer will
// result in compilation errors.
type UnsafeForwarderServiceServer interface {
	mustEmbedUnimplementedForwarderServiceServer()
}

func RegisterForwarderServiceServer(s grpc.ServiceRegistrar, srv ForwarderServiceServer) {
	// If the following call pancis, it indicates UnimplementedForwarderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ForwarderService_ServiceDesc, srv)
}

func _ForwarderService_RegisterChannelSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterChannelSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwarderServiceServer).RegisterChannelSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwarderService_RegisterChannelSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwarderServiceServer).RegisterChannelSession(ctx, req.(*RegisterChannelSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForwarderService_RemoveChannelSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveChannelSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwarderServiceServer).RemoveChannelSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForwarderService_RemoveChannelSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwarderServiceServer).RemoveChannelSession(ctx, req.(*RemoveChannelSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ForwarderService_ServiceDesc is the grpc.ServiceDesc for ForwarderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForwarderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "forwarder.ForwarderService",
	HandlerType: (*ForwarderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterChannelSession",
			Handler:    _ForwarderService_RegisterChannelSession_Handler,
		},
		{
			MethodName: "RemoveChannelSession",
			Handler:    _ForwarderService_RemoveChannelSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/forwarder/forwarder.proto",
}
